/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.EnergiaSolar.gui.Cliente;

import com.mycompany.EnergiaSolar.src.main.java.poo.example.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Tasso
 */
public class OrcamentoCliente extends javax.swing.JFrame {

    /**
     * Creates new form OrcamentoCliente
     */
    
    
    public OrcamentoCliente() {
        initComponents();
        
        configurarComponentes();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void configurarComponentes() {
        // Remove o texto padrão nos campos de texto
        telefone.setText("Cliente(Telefone)");
        consumo.setText("Consumo(Kwh)");
        cidade.setText("Estado");
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        consumo = new javax.swing.JTextField();
        botaoGerarOrcamento = new javax.swing.JButton();
        cidade = new javax.swing.JTextField();
        botaoVoltare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Orçamento");

        telefone.setText("Cliente(Telefone)");

        consumo.setText("Consumo(Kwh)");
        consumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoActionPerformed(evt);
            }
        });

        botaoGerarOrcamento.setBackground(new java.awt.Color(0, 0, 153));
        botaoGerarOrcamento.setForeground(new java.awt.Color(255, 255, 255));
        botaoGerarOrcamento.setText("Gerar orçamento");
        botaoGerarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarOrcamentoActionPerformed(evt);
            }
        });

        cidade.setText("Cidade");
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });

        botaoVoltare.setBackground(new java.awt.Color(0, 0, 153));
        botaoVoltare.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltare.setText("Voltar");
        botaoVoltare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoVoltare))
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(botaoGerarOrcamento)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltare))
                .addGap(18, 18, 18)
                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(botaoGerarOrcamento)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoActionPerformed
        
    }//GEN-LAST:event_consumoActionPerformed

    private void botaoGerarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarOrcamentoActionPerformed
        String clienteTelefone = telefone.getText();
        String consumoTexto = consumo.getText();
        String cidadeCliente = cidade.getText();

        if (clienteTelefone.isEmpty() || consumoTexto.isEmpty() || cidadeCliente.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        float consumoMedio;
        try {
            consumoMedio = Float.parseFloat(consumoTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor numérico válido para o consumo!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cliente cliente = AplicacaoService.obterCliente(clienteTelefone);
        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!cliente.obterProjetos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cliente já possui um projeto em andamento!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        cliente.solicitarProjeto(consumoMedio);
        Projeto projeto = cliente.obterProjetos().get(0); 

        float custoPlacas = 5000; // Valor de exemplo
        float custoInversores = 3000; // Valor de exemplo
        float orcamentoTotal = AplicacaoService.calcularOrcamento(custoPlacas, custoInversores);

        AplicacaoService.enviarOrcamento(cliente, projeto, orcamentoTotal);

        JOptionPane.showMessageDialog(this, "Orçamento gerado com sucesso! Valor: R$" + orcamentoTotal);

        ProjetoCliente projetoClienteTela = new ProjetoCliente();
        projetoClienteTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoGerarOrcamentoActionPerformed
   

    
    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed

    private void botaoVoltareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltareActionPerformed
        new InicioCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltareActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGerarOrcamento;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton botaoVoltar1;
    private javax.swing.JButton botaoVoltar2;
    private javax.swing.JButton botaoVoltar3;
    private javax.swing.JButton botaoVoltar4;
    private javax.swing.JButton botaoVoltare;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField consumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField telefone;
    // End of variables declaration//GEN-END:variables
}
